style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

OtusRuleSet:
  ComposeModifierMissingRule:
    active: false
  GlobalScopeRule:
    active: true
  TopLevelCoroutineInSuspendFunRule:
    active: true
